### ISSUE TITLE
The module is not working in Slicer

### ISSUE THREAD

**Issue by juanprietob** [NIRALUser/RigidAlignment#3]
@bpaniagua @jcfr This module is nor working when launched in Slicer. 

The wrapper for the RigidAlingmentModule was removed in the commit https://github.com/NIRALUser/RigidAlignment/commit/ac5c9cdb3b52db0ecc71f5d223f36aaba4ca96dc

The call on line 
https://github.com/NIRALUser/GROUPS/blob/master/Modules/Scripted/RigidAlignmentModule/RigidAlignmentModule.py#L175 fails

**Comment by bpaniagua** [comment]
@vicory will look into it.
We have gotten that reported here also: https://github.com/Kitware/SlicerSALT/issues/146

We are working on SlicerSALT 2.0
There will be few changes that will be coming to the SPHARM, MSFDA, and GROUPS repos. Will you be around to review/merge PRs?

**Comment by juanprietob** [comment]
Yes, I can merge the PR. 
Also, I noticed that the current built system for GROUPS/RigidAlignment is not working when packaged as an extension. 
The CLI modules for RigidAlignment and SRmesh are packed in a directory that is not deployed when GROUPS is installed as an extension. 

![image](https://user-images.githubusercontent.com/7086191/55991503-061a7300-5c70-11e9-9a26-bee9f2f4940f.png)

The directories outside the directory 'Extensions-27931' won't be installed, therefore, the RigidAlignment and SRemesh are lost. 

Can these CLI be included besides the Gropus CLI?

**Comment by jcfr** [comment]
Closing. It was reported as fixed in https://github.com/Kitware/SlicerSALT/issues/146#issuecomment-528907635 (most likely through https://github.com/NIRALUser/GROUPS/pull/34)
