### ISSUE TITLE
Re-fork repositories to avoid confusion

### ISSUE THREAD

**Issue by jcfr** [NIRALUser/RigidAlignment#4]
@ilwoolyu To avoid confusion, could you delete your project `ilwoolyu/RigidAlignment` and re-fork the one hosted in the `NIRALUser` organization. See https://github.com/NIRALUser/RigidAlignment

The fork graph currently shows this:

![image](https://user-images.githubusercontent.com/219043/70098817-2cc05c00-15fb-11ea-9dbe-36b9dd6c2107.png)

@pdedumast: After @ilwoolyu is done, you may have to do the same.

Thanks :pray:

**Comment by ilwoolyu** [comment]
Done.

**Comment by pdedumast** [comment]
👍

**Comment by jcfr** [comment]
Thanks everyone :+1:
